### ISSUE TITLE
Evaluate feasibleness of a port to Avalonia

### ISSUE THREAD

**Issue by milleniumbug** [DidacticalEnigma/DidacticalEnigma#35]
Currently project doesn't use any third party libraries for WPF outside of analyzer, so it may be easy to get it to work on Avalonia. Potential pain point: `FlowDocument`.

**Comment by milleniumbug** [comment]
Blocked by https://github.com/AvaloniaUI/Avalonia/pull/1689

**Comment by milleniumbug** [comment]
TabControl and formatted text works now, but Japanese IME doesn't seem to work (it displays the usual window in the corner and stuff is typed there, rather than being displayed near the input)

**Comment by milleniumbug** [comment]
Japanese IME on Linux doesn't work at all https://github.com/AvaloniaUI/Avalonia/issues/2076

This is a blocker that prompts to explore alternative approaches to GUI.

**Comment by kekekeks** [comment]
Ehm, I'm pretty sure that Japanese IME is available through iBus and fcitx. I was testing with mozc, not sure about other engines.
